name = "BOCD"
uuid = "c50d80af-7a5e-4c76-8308-72a9003b1873"
authors = ["PedroPizarro <pedroapizarro@usp.br>"]
version = "0.2.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25.118"
